apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-test
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
      - name: gke-test
        image: LOCATION-docker.pkg.dev/niladariya-454521/REPOSITORY/IMAGE:TAG
        ports:
        - containerPort: 8080